 Adjust atlases for stereotactic navigation for Focused Ultrasound experimentation
 ======
 
 This notebook adjust the public domain Nifti 3D mouse and rat atlases to be conformal for stereotactic navigation.
 
 Source data was downloaded from the **Scalable Brain Atlas**:
 
 https://scalablebrainatlas.incf.org
 
 
 Each atlas was manually inspected to recenter the 0 at Bregma. The size in mm is important to calibrate the area of the SVG scalable templates.
 
 # Citation
 
 When using these atlases in your research, plase be sure of citing the following references
 
## P56 Allen mouse atlas
 * Lein ES, Hawrylycz MJ, Ao N, et al. (2007) "Genome-wide atlas of gene expression in the adult mouse brain." Nature 445(7124):168-76. [doi 10.1038/nature05453]
 
 * Rembrandt Bakker, Paul Tiesinga, Rolf Kötter (2015) 
 "The Scalable Brain Atlas: instant web-based access to public brain atlases and related content." 
Neuroinformatics. http://link.springer.com/content/pdf/10.1007/s12021-014-9258-x (author copy: arXiv:1312.6310)
 
 
## Walxhom rat atlas
* Papp EA, Leergaard TB, Calabrese E, Johnson GA, Bjaalie JG (2014) "Waxholm Space atlas of the Sprague Dawley rat brain" NeuroImage 97:374-386. [doi 10.1016/j.neuroimage.2014.04.001]

* Kjonigsen LJ, Lillehaug S, Bjaalie JG, Witter MP, Leergaard TB (2015) "Waxholm Space atlas of the rat brain hippocampal region: Three-dimensional delineations based on magnetic resonance and diffusion tensor imaging." NeuroImage 108:441–449. [doi 10.1016/j.neuroimage.2014.12.080]

* Sergejeva M, Papp EA, Bakker R, Gaudnek MA, Okamura-Oho Y, Boline J, Bjaalie JG, Hess A (2015) "Anatomical landmarks for registration of experimental image data to volumetric rodent brain atlasing templates." Journal of Neuroscience Methods 240:161-169. [doi 10.1016/j.jneumeth.2014.11.005]
 
* Rembrandt Bakker, Paul Tiesinga, Rolf Kötter (2015) 
 "The Scalable Brain Atlas: instant web-based access to public brain atlases and related content." 
Neuroinformatics. http://link.springer.com/content/pdf/10.1007/s12021-014-9258-x (author copy: arXiv:1312.6310)

## VSNetal11 rat atlas
* Valdés-Hernández PA, Sumiyoshi A, Nonaka H, Haga R, Aubert-Vásquez E, Ogawa T, Iturria-Medina Y, Riera JJ, Kawashima R (2011) "An in vivo MRI template set for morphometry, tissue segmentation, and fMRI localization in rats" Front Neuroinform 5(26). [doi 10.3389/fninf.2011.00026]
 
* Rembrandt Bakker, Paul Tiesinga, Rolf Kötter (2015) 
 "The Scalable Brain Atlas: instant web-based access to public brain atlases and related content." 
Neuroinformatics. http://link.springer.com/content/pdf/10.1007/s12021-014-9258-x (author copy: arXiv:1312.6310)
 


# License
The code in this notebook (and only the code) is shared with the BSD 3-clause license
```
BSD 3-Clause License

Copyright (c) 2018, ProteusMRIgHIFU
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

```

In [1]:
import nibabel
import numpy as np

In [27]:
a=nibabel.load('../Mouse/P56/P56_Atlas.nii.gz')


newaffine = a.affine.copy()
newaffine[1,3]=a.affine[2,3]
newaffine[2,3]=a.affine[1,3]
newaffine[1,1]*=-1
newaffine[1,3]-=-(10.78) # this makes bregma at the edge of the 3D array
newaffine[2,3]-=0.15
newdata=np.swapaxes(a.get_data(),1,2)
img = nibabel.nifti1.Nifti1Image(newdata, newaffine)

img.to_filename('../Mouse/P56/P56_Atlas-Stereo.nii.gz')

print 'size in mm', np.array(img.shape)*0.025
print 'coordinates of origing for SVG \n', np.dot(img.affine,np.array([[0],[newdata.shape[1]],[0],[1]]))
print newaffine

size in mm [ 11.4   8.   13.2]
coordinates of origing for SVG 
[[-5.69999981]
 [-0.04500017]
 [-7.97499981]
 [ 1.        ]]
[[ 0.025       0.          0.         -5.69999981]
 [ 0.         -0.025       0.          7.95499995]
 [ 0.          0.          0.025      -7.97499981]
 [ 0.          0.          0.          1.        ]]


In [28]:
a=nibabel.load('../Rat/VSNetal11/brain-nmdrat30_ras.nii.gz')
newAffine=a.affine.copy()


newAffine[1,3]=a.affine[2,3]
newAffine[2,3]=a.affine[1,3]
newAffine[0:3,:]/=10.
newAffine[1,1]*=-1
newAffine[1,3]-=-(16.19)
newAffine[3,3]-=0.214
newdata=np.swapaxes(a.get_data(),1,2)

img = nibabel.nifti1.Nifti1Image(newdata, newAffine)

img.to_filename('../Rat/VSNetal11/brain-nmdrat30_ras_stereo.nii.gz')

a=img

print 'size in mm',  np.array(a.shape)*0.125

print 'coordinates of origing for SVG \n', np.dot(a.affine,np.array([[0],[a.shape[1]],[0],[1]]))
print newAffine

size in mm [ 17.    12.75  22.5 ]
coordinates of origing for SVG 
[[ -8.29278259]
 [ -1.1278421 ]
 [-15.66135254]
 [  0.786     ]]
[[  0.125        0.           0.          -8.29278259]
 [  0.          -0.125        0.          11.6221579 ]
 [  0.           0.           0.125      -15.66135254]
 [  0.           0.           0.           0.786     ]]


In [29]:
a=nibabel.load('../Rat/Walxhom/WHS_SD_rat_atlas_v2.nii.gz')


newAffine=a.affine.copy()


newAffine[1,3]=a.affine[2,3]
newAffine[2,3]=a.affine[1,3]
newdata=np.swapaxes(a.get_data(),1,2)
newAffine[1,1]*=-1
newAffine[0,3]-=1.1718750-1.33
newAffine[1,3]-=(-26.64)

img = nibabel.nifti1.Nifti1Image(newdata, newAffine)

img.to_filename('../Rat/Walxhom/WHS_SD_rat_atlas_v2_stereo.nii.gz')

a=img


print 'size in mm', np.array(a.shape)*0.0390625

print 'coordinates of origing for SVG \n', np.dot(a.affine,np.array([[0],[a.shape[1]],[0],[1]]))
print newAffine

size in mm [ 20.  20.  40.]
coordinates of origing for SVG 
[[ -9.373125 ]
 [ -3.0475   ]
 [-24.3359375]
 [  1.       ]]
[[  0.0390625   0.         -0.         -9.373125 ]
 [  0.         -0.0390625  -0.         16.9525   ]
 [  0.          0.          0.0390625 -24.3359375]
 [  0.          0.          0.          1.       ]]


_______
Preparation of SVG atlases for stereotactic navigation
===

We also prepared the label location of the atlases for their display in the SVG viewer. The location of the each label 
is extracted from the SVG directly and the provided files for the labels are used to generate JSON files that provide the location of each label in the SVG coordinate system. See below example of rendering.

<img src="./Example.png" width="400">

The source SVG files in the the **Scalable Brain Atlas** project have different canvas size depending on the atlas. for our purposes, we scaled the rat atlases to have a similar canvas size as the mouse atlas. This simplified the atlases were displayed similarly. Otherwise the labels and lines may appear thicker or bigger. We use the tool `rsvg-convert` and the [svgscale script](./svgscale) provided in https://github.com/numixproject/numix-tools/blob/master/numix-tools/svgscale to perform the scaling. For this atlases, we used `svgscale 430` to match the same canvas as the mouse atlas. The `svgscale` script is shared under GNU General Public License v3.0 (https://github.com/numixproject/numix-tools/blob/master/LICENSE) and is shown below:


In [15]:
import xml.etree.ElementTree as et
import math
import csv
import json
from svgpathtools import svg2paths, wsvg
import svgpathtools
from glob import glob
import numpy as np
import os

def PrepareAtlasForMorpheus(path,auxpath=None):
    with file(path + os.sep + 'rgb2acr.json','r') as f:
        rgb2acr = json.load(f)

    ListFiles=glob(path + os.sep +'*.svg')
    ListFiles.sort()
    
    if auxpath:
        AuxListFiles=glob(auxpath + os.sep +'*.svg')
        AuxListFiles.sort()
    else:
        AuxListFiles=glob(path + os.sep +'*.svg')
        AuxListFiles.sort()

    NUM_SAMPLES = 100
    vertices=np.zeros((NUM_SAMPLES,2))

    for fname,auxfile in zip(ListFiles,AuxListFiles):
        
        filename = fname.split('.svg')[0]

        paths, attributes = svg2paths(fname)
        auxpaths, auxattributes = svg2paths(auxfile)

        ListCenters=[]

        for element,attr,auxelement,auxattr in zip(paths,attributes,auxpaths, auxattributes):
            rgb=auxattr['fill'][1:]
            if rgb  not in rgb2acr:
                continue
            for i in range(NUM_SAMPLES):
                p=element.point(float(i)/(float(NUM_SAMPLES)-1.0))
                vertices[i,:]=[np.real(p),np.imag(p)]
            entry={'center':vertices.mean(axis=0).tolist(),'acr':rgb2acr[rgb]}
            ListCenters.append(entry)
        with file(filename+'-acr.json','w') as f:
            json.dump(ListCenters,f)
    print 'done'
    

In [16]:
path='../Mouse/P56'
PrepareAtlasForMorpheus(path)

path='../Rat/VSNetal11/'
auxpath='../Rat/VSNetal11/OriginalSVG'
PrepareAtlasForMorpheus(path,auxpath)

path='../Rat/Walxhom/'
auxpath='../Rat/Walxhom/OrigSVG'
PrepareAtlasForMorpheus(path,auxpath)

done
done
done
